name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: install
        run: yarn

      - name: build
        run: yarn build

      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v2.0.1
        with:
          github-token: ${{ secrets.github_token }}
